apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-controller
  namespace: argocd
spec:
  project: default
  source:
    chart: actions-runner-controller
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    targetRevision: v0.23.7
    helm:
      releaseName: actions-runner-controller
  destination:
    name: in-cluster
    namespace: actions-runner-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true