apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/refs/tags/v2.14.6/manifests/install.yaml

patches:
- path: ./argocd-cm.yaml
- path: ./argocd-rbac-cm.yaml