# https://taskfile.dev

version: '3'

tasks:
  install:
    cmds:
      - kubectl config set-context kind-{{.cluster_mgmt}}
      - kubectl create ns argocd
      - kubectl apply -k .

  port-forward:
    cmds:
      - kubectl port-forward svc/argocd-server -n argocd 8080:443

  get-password:
    cmds:
      - kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath='{.data.password}' | base64 -d