apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
  labels:
    app-type: application
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters: {}
      # selector:
      #   matchLabels:
      #     # only add app to worker clusters
      #     role: worker
  template:
    metadata:
      name: '{{.name}}-guestbook'
      finalizers:
        # cascade delete app resources
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL:  https://github.com/dgmorales/k8s-lab.git
        targetRevision: HEAD
        path: apps/manifests/guestbook/
      destination:
        server: '{{.server}}'
        namespace: guestbook
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true