apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app-type: cluster-addon
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io/
    targetRevision: v1.17.2
    helm:
      releaseName: cert-manager
      valuesObject:
        crds:
          enabled: true
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true