apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: argocd-lab-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: dgmorales/k8s-lab